-- CreateTable
CREATE TABLE "User" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "email" STRING NOT NULL,
    "userName" STRING NOT NULL,
    "password" STRING NOT NULL,
    "firstName" STRING NOT NULL,
    "lastName" STRING NOT NULL,
    "birthday" DATE NOT NULL,
    "dateCreated" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Book" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "title" STRING NOT NULL,
    "genreID" INT4 NOT NULL,
    "link" STRING,
    "description" STRING NOT NULL,
    "authorName" STRING NOT NULL,
    "dateCreated" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Book_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Page" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "chapterName" STRING NOT NULL,
    "pageNumber" INT4 NOT NULL,
    "body" STRING NOT NULL,
    "bookID" INT4 NOT NULL,
    "dateCreated" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "lastUpdatedBy" INT4 NOT NULL,

    CONSTRAINT "Page_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Genre" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "genre" STRING NOT NULL,

    CONSTRAINT "Genre_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "History" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "userID" INT4 NOT NULL,
    "pageRef" INT4 NOT NULL,
    "bookRef" INT4 NOT NULL,
    "prevBody" STRING NOT NULL,
    "currBody" STRING NOT NULL,
    "commit" STRING NOT NULL,
    "bookID" INT4,
    "pageID" INT4,
    "dateUpdated" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "History_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");

-- CreateIndex
CREATE UNIQUE INDEX "User_userName_key" ON "User"("userName");

-- AddForeignKey
ALTER TABLE "Book" ADD CONSTRAINT "Book_authorName_fkey" FOREIGN KEY ("authorName") REFERENCES "User"("userName") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Page" ADD CONSTRAINT "Page_bookID_fkey" FOREIGN KEY ("bookID") REFERENCES "Book"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "History" ADD CONSTRAINT "History_bookID_fkey" FOREIGN KEY ("bookID") REFERENCES "Book"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "History" ADD CONSTRAINT "History_pageID_fkey" FOREIGN KEY ("pageID") REFERENCES "Page"("id") ON DELETE SET NULL ON UPDATE CASCADE;
